name: java-spring-crud-mvc-sample Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: stCarolas/setup-maven@v4.3
    - uses: actions/checkout@v3
    - name: Maven / Docker - build and push
      run:  |
        mvn -B package --file pom.xml
        docker login -u ${{secrets.DOCKER_USER}} -p ${{secrets.DOCKER_PASSWORD}} 
        docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/java-spring-crud-mvc-sample:$(git rev-parse --short "$GITHUB_SHA")
        docker push ${{secrets.DOCKER_USER}}/java-spring-crud-mvc-sample:$(git rev-parse --short "$GITHUB_SHA")
        docker build . --file Dockerfile --tag ${{secrets.DOCKER_USER}}/java-spring-crud-mvc-sample:latest
        docker push ${{secrets.DOCKER_USER}}/java-spring-crud-mvc-sample:latest
