name: java-spring-crud-mvc-sample Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: stCarolas/setup-maven@v4.3
    - uses: actions/checkout@v3
    - name: Maven and Docker build 
      run:  |
        mvn -B package --file pom.xml
        docker build . --file Dockerfile --tag java-spring-crud-mvc-sample:$(date +%s)
