name: java-spring-crud-mvc-sample Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: stCarolas/setup-maven@v4.3
    - name: Maven Build
      run:  |
        ls -l
        mvn -B package --file pom.xml
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag java-spring-crud-mvc-sample:$(date +%s)
